workflows:
  dupplifilter-ios-only:
    name: DuppliFilter Build iOS Only
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_DIR: build
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - gianluca@depino.eu
        notify:
          success: true
          failure: true
