name: dupplifilter
description: App Flutter DuppliFilter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker:
    path: C:/Users/info/Documents/file_picker_ios_only
  image: ^4.1.3
  share_plus: 11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
